sudo: false

language: python

env:
    global:
        - NUMPY_VERSION=1.9

matrix:
    include:
        # All the versions of Python.
        - python: 2.6
        - python: 2.7
        - python: 3.3
        - python: 3.4

        # Old versions of NumPy.
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 3.4
          env: NUMPY_VERSION=1.8

        - python: 2.7
          env: NUMPY_VERSION=1.7
        - python: 3.3
          env: NUMPY_VERSION=1.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION scipy pytest setuptools h5py
    - pip install pytest-cov coveralls

script:
    - python setup.py test -a "--cov emcee -v"

after_success:
    - coveralls
